[[projects]]
title = "ProjectTitle"
connection_schema = "mongodb"
connection_type = "direct"
db_type = "mongodb"
db_host = "0.0.0.0"
db_port = "27017"
db_username = "mongodb"
db_password = "mongodb"
db_name = "db"
ssh_tunnel = { }

  [projects.connection_params]
  authSource = "db"
